name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        
    - name: Install Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Debug --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Check Formatting
      run: dotnet format --verify-no-changes

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Build ${{ matrix.os }}
        path: "**/bin/Debug/net7.0"
