name: Automated API tests using Postman CLI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  start-api:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4.1.1
        - name: Run API
          run: dotnet run --project CentralHub.Api/CentralHub.Api.csproj 

  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "31208196-ebe740bc-2741-48ef-bdb6-e9ad85e8d39a"